name = "python-modlang"
version = "0.1.0"
defaultTargets = ["python-modlang"]

[[lean_lib]]
name = "PythonModlang"

[[lean_exe]]
name = "python-modlang"
root = "Main"

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4"
rev = "master"
version = "v4.27.0"